### PR TITLE
The Next Web responsive web page

### PR DESCRIPTION
**Pull request by tGodson**
This is a responsive web page of the Next Web magazine. Built with HTML and CSS.

### CODE REVIEW

**Comment by uryelah** [comment]
Hello **Godson Tendongze Zeingkeang & Arafat Akata**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all great job following the original site typography and colors. It looks really nice!🌟**

There are still some issues to fix, mainly to do with code style and responsiveness, but I'm sure it will be very easy for you guys considering the level of the work you delivered. Make sure to revisit the [original page](https://thenextweb.com/) and compare how it behaves on screen resize so you can compare where your clone is not the same. 
---------     

## Required Changes 🏗 👷‍♀ 

- [x] Make sure to lint your project and enable Stickler.

- [ ]Remove your commented out CSS code, if you still want to revisit an older version of the code you can store it at a different branch.

- [x] Prefer specificity over the use of '!important' on CSS rules.

- [x] On wide screens make sure the Latest News images all have the same height and are aligned both on top and bottom.
Notice below how the images have slightly mismatching sizes:
Screenshot_2020-04-24 The Next Web(2)

---

- [x]  Make sure there's no gap between the main navbar and the yellow bar under it:
Screenshot_2020-04-24 The Next Web(1)


-----

- [x] On medium devices the navbar should change to include the top black bar and the main article image should not have the logo and gradient over it.
Compare your version and the original one below:
Screenshot_2020-04-24 The Next Web(3)
Screenshot_2020-04-24 TNW - International technology news, business and culture


----

- [x] Make sure the yellow bar doesn't increase its height on small screens:
Screenshot_2020-04-24 The Next Web(4)


----

- [x] On medium-size screens the 'Latest News' section should contain 3 articles per row, not 4.

-----

- [x] The categories sections, 'App', 'Gear', etc, should contain 2 articles per row on medium-size screens.

----

- [x] The 'Latest Deals ' section should contain 3 articles per row on medium-screens.

---- 

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @haraphat01 & @tGodson  :wave:
-
You have done a splendid job implementing the requested changes.! :tada: Keep it up.
We are almost done here, just some few changes we need to sort out that we might have bypassed (see review comment).
##
- Remove all the inline styling from the markup and let's move them to the CSS file.
- Update your README live link.
- Good job with the summary. We can always improve on it by highlighting what we have carried out in the project's PR to guide the reviewer on what has been achieved so far.  
##
Please make these changes and submit another review request.
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Comment by tGodson** [comment]
-updated the readme file 
-removed all inline styles

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon: 

Hi @haraphat01 and @tGodson, great work :+1: congratulations for making all the changes requested by the previous TSE's, thanks to them and your hard work, the project now looks great :smile: 
Before you merge to master, let us add margin-top to the ```<div class="section-1-1">```, the TNW logo is hiding behind the nav. We can also add email to our readme on the author section

Go ahead and merge to master :+1: 
_Happy coding_ :man_technologist: 
Daniel Larbi Addo on slack

**Pull request merged**
